(function(root){
  'use strict';
  const E=root.GrooveEngine,C=root.PracticeCatalog,T=root.TrainingEngine,$=id=>document.getElementById(id),clone=T.clone;
  let connected=null,motif=null,mode='connection',frame=0,locked=false;
  const audio={...root.EarEngine.defaults,repeats:0,gap:0,countIn:1,drums:false,clickMode:'all'};
  const player=new root.EarPlayer((message,state)=>{const id=mode==='connection'?'tcStatus':'tmStatus';if($(id))$(id).textContent=message;if(mode==='connection'&&$('tcPlay'))$('tcPlay').textContent=state==='preparing'?'■ 启动中':state===true?'■ 停止':'▶ 播放连接';});
  const opts=(map,value)=>Object.entries(map).map(([k,v])=>`<option value="${k}" ${String(value)===k?'selected':''}>${v}</option>`).join('');
  const field=(name,id,map,value)=>`<label>${name}<select id="${id}">${opts(map,value)}</select></label>`;
  const num=(name,id,value,min,max)=>`<label>${name}<input id="${id}" type="number" value="${value}" min="${min}" max="${max}"></label>`;
  function init(){
    const card=document.createElement('section');card.id='connectionPanel';card.className='card training-section';
    card.innerHTML=`<div class="card-head"><h2>和弦连接</h2><span class="small">让下一和弦听起来自然</span></div><div class="training-body"><div class="training-fields">${field('主音','tcKey',Object.fromEntries(E.names.map((n,i)=>[i,n])),0)}${field('调式 / 音阶','tcScale',C.scales,'major')}${field('进行','tcProgression',{'1,4,0':'II – V – I','0,5,1,4':'I – VI – II – V','0,4,5,3':'I – V – VI – IV','0,3':'I – IV'},'1,4,0')}${field('连接目标','tcTarget',T.targets,'nearest')}${field('句型难度','tcDifficulty',{easy:'基础 · 四分与八分',medium:'进阶 · 八分线条',hard:'挑战 · 十六分切分'},'medium')}${field('弦组','tcStrings',{all:'全部六弦',treble:'高音 1–3 弦',bass:'低音 4–6 弦'},'all')}${num('起始品','tcMin',3,0,12)}${num('结束品','tcMax',7,0,12)}${field('每和弦拍数','tcBeats',{2:'2 拍',4:'4 拍',8:'8 拍'},4)}${num('速度 BPM','tcTempo',80,40,220)}</div><div class="training-actions"><button class="btn primary" id="tcGenerate">生成连接</button><button class="btn" id="tcPlay">▶ 播放连接</button><label><input id="tcLoop" type="checkbox" checked>循环</label><label><input id="tcDemo" type="checkbox" checked>吉他示范</label><label>分段 <select id="tcSection"><option value="all">完整进行</option></select></label><label>音量 <input id="tcVolume" type="range" min="0" max="100" value="90" aria-label="和弦连接音量"></label><button class="btn" id="tcRound">记录一次实际练习</button></div><p class="training-help">强拍落在当前和弦目标音，弱拍组织调内旋律，小节末可用调内或半音趋近解决到下一和弦。关闭示范后保留节拍器，供自己演奏。</p><p id="tcStatus" role="status">准备生成</p><p id="tcNow" class="training-now"></p><div id="tcScore" class="training-score"></div></div>`;
    document.querySelector('.grid').after(card);
    $('tcGenerate').onclick=()=>{try{connected=T.connection(readConnection());renderConnection();root.TrainingHub?.exerciseChanged('connection',snapshot('connection'));}catch(e){$('tcStatus').textContent=e.message;}};
    $('tcPlay').onclick=()=>mode==='connection'&&(player.playing||player.preparing)?stop():playConnection();
    $('tcRound').onclick=()=>{if(!root.TrainingHub?.step('connection'))$('tcStatus').textContent='请先从「今日练习」开始或继续和弦连接任务，再记录实际练习。';};
    ['tcLoop','tcDemo','tcSection'].forEach(id=>$(id).onchange=stop);
    $('tcVolume').oninput=()=>player.mix({...audio,guitarVolume:+$('tcVolume').value});
    card.addEventListener('change',e=>{if(!['tcLoop','tcDemo','tcVolume','tcSection','tcView','tcNotation'].includes(e.target.id)){stop();$('tcStatus').textContent='设置已更改 · 请生成连接以应用';root.TrainingHub?.deviate('connection');}});
    const m=document.createElement('section');m.id='motifDevelopment';m.className='card training-section';m.hidden=true;
    m.innerHTML=`<div class="card-head"><h2>动机发展 · A → B</h2><span class="small">每次只改一个维度</span></div><div class="training-body"><div class="training-fields">${field('主音','tmKey',Object.fromEntries(E.names.map((n,i)=>[i,n])),0)}${field('调式 / 音阶','tmScale',C.scales,'major')}${field('调内和弦','tmDegree',{0:'I',1:'II',2:'III',3:'IV',4:'V',5:'VI',6:'VII'},0)}${field('变化方式','tmType',T.changes,'ending')}${num('速度 BPM','tmTempo',80,40,220)}</div><div class="training-actions"><button class="btn" id="tmSource">生成原动机 A</button><button class="btn" id="tmCurrent">从当前律动提取 A</button><label><input id="tmLock" type="checkbox">锁定 A</label><button class="btn primary" id="tmVary">只换 B</button><button class="btn" id="tmSave">收藏 A / B</button><label>收藏<select id="tmFavorites"><option value="">选择收藏</option></select></label><button class="btn" id="tmLoad">载入</button></div><div class="training-ab"><div><h3>A · 原动机</h3><div id="tmA" class="training-score"></div></div><div><h3>B · 单维变奏 <small>亮色边框 = 改变</small></h3><div id="tmB" class="training-score"></div></div></div><div class="training-actions"><button class="btn" data-motif-play="a">▶ A</button><button class="btn" data-motif-play="b">▶ B</button><button class="btn" data-motif-play="ab">▶ A → B</button><button class="btn" data-motif-play="turn">▶ A → 留白自己弹</button><button class="btn" id="tmStop">■ 停止</button><label>音量<input id="tmVolume" type="range" min="0" max="100" value="90" aria-label="动机发展音量"></label><button class="btn" id="tmAttempt">已尝试这个变奏</button></div><p id="tmStatus" role="status">先建立原动机，再练习单维变化。</p><p class="training-help">简谱相对当前调主音；音名附八度，底部是弦 / 品与起点 / 时值（四分拍）。留白段不播放吉他，保留节拍器；练过后请主动记录，不自动评分。</p></div>`;
    document.querySelector('.motif-body').append(m);
    m.classList.add('motif-development-inline');
    $('tmSource').onclick=()=>safeMotif(()=>makeMotif());
    $('tmCurrent').onclick=()=>safeMotif(fromGroove);
    $('tmVary').onclick=()=>safeMotif(()=>{if(!motif)makeMotif();else {stop();motif.type=$('tmType').value;motif.b=T.vary(motif.a,motif.type);renderMotif();root.TrainingHub?.exerciseChanged('motif',snapshot('motif'));}});
    $('tmLock').onchange=()=>{locked=$('tmLock').checked;};
    $('tmType').onchange=()=>{$('tmStatus').textContent='点击「只换 B」应用变化方式';root.TrainingHub?.deviate('motif');};
    for(const id of ['tmKey','tmScale','tmDegree','tmTempo'])$(id).onchange=()=>{stop();$('tmStatus').textContent='参数已更改 · 生成原动机以应用';root.TrainingHub?.deviate('motif');};
    m.querySelectorAll('[data-motif-play]').forEach(b=>b.onclick=()=>playMotif(b.dataset.motifPlay));
    $('tmStop').onclick=stop;$('tmVolume').oninput=()=>player.mix({...audio,guitarVolume:+$('tmVolume').value});
    $('tmAttempt').onclick=()=>{if(motif){const added=root.TrainingHub?.step('motif',JSON.stringify(motif.b.events.map(e=>[e.start,e.duration,e.note?.midi])));$('tmStatus').textContent=added?'已记录这次变奏尝试 · 点击「只换 B」继续':'未重复计数：请确认任务正在计时，并生成一个尚未记录的变奏。';}};
    $('tmSave').onclick=()=>{if(motif)root.TrainingHub?.saveMotif(snapshot('motif'));};
    $('tmLoad').onclick=()=>root.TrainingHub?.loadMotif($('tmFavorites').value);
    const tabs=document.createElement('div');tabs.className='motif-mode-tabs';tabs.innerHTML='<button class="btn active" id="tmLearn" aria-pressed="true">1 · 原句跟弹</button><button class="btn" id="tmDevelop" aria-pressed="false">2 · 发展这条动机</button>';
    document.querySelector('.motif-body').prepend(tabs);
    $('tmLearn').onclick=()=>setMotifView(false);$('tmDevelop').onclick=()=>safeMotif(()=>{if(!motif||motif.a.key!==state.root||motif.a.scale!==state.mode||motif.a.chord?.degree!==Math.max(0,state.chord)||motif.sourceSignature!==lastMotifPitches.join(',')){locked=false;$('tmLock').checked=false;setSource(T.motif({key:state.root,scale:state.mode,degree:Math.max(0,state.chord),min:state.start,max:state.end,pitches:lastMotifPitches.slice(),phrase:'steady',tempo:80}));motif.sourceSignature=lastMotifPitches.join(',');}setMotifView(true);});
    const phrase=document.createElement('div');phrase.className='training-fields';phrase.innerHTML=field('原句节奏','tmPhrase',{steady:'八拍均分 · 保留原动机',mixed:'长短句 · 八分与停留',sync:'切分句 · 强弱拍呼应'},'mixed')+field('循环练习','tmRepeat',{1:'一轮',3:'三轮',0:'持续循环'},3);
    m.querySelector('.training-fields').after(phrase);
    $('tmCurrent').hidden=true;['tmKey','tmScale','tmDegree'].forEach(id=>$(id).closest('label').hidden=true);
    $('tmPhrase').onchange=()=>{$('tmStatus').textContent='节奏选择将用于下一条原句；当前 A 保持不变。';};
    const guidance=document.createElement('p');guidance.id='tmGuidance';guidance.className='motif-guidance';m.querySelector('.training-body').prepend(guidance);
    $('tmVary').textContent='给一个 B 示例';$('tmSource').textContent='换一条两小节原句';$('tmAttempt').textContent='我已弹出自己的变化';
    installGroove();document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);
  }
  function installGroove(){$('ggMotifEntry')?.remove();}
  function setMotifView(develop){stop();$('motifDevelopment').hidden=!develop;document.querySelector('.motif-modal').classList.toggle('developing',develop);for(const [id,on]of [['tmLearn',!develop],['tmDevelop',develop]]){$(id).classList.toggle('active',on);$(id).setAttribute('aria-pressed',String(on));}document.querySelector('.motif-modal').scrollTop=0;}
  function openMotif(){renderMotifShell();setMotifView(true);renderMotif();}
  function renderMotifShell(){motifReturnFocus=$('motifBtn');$('motifModal').classList.add('open');$('motifModal').setAttribute('aria-hidden','false');$('motifTitle').textContent=(motif?.a.chord?.name||'和弦')+' · 动机训练';$('motifContext').textContent='学会原句，再只改一个维度；不是反复随机换音。';$('motifClose').focus();}
  function readConnection(){return {key:+$('tcKey').value,scale:$('tcScale').value,progression:$('tcProgression').value,target:$('tcTarget').value,difficulty:$('tcDifficulty').value,strings:$('tcStrings').value,min:+$('tcMin').value,max:+$('tcMax').value,beats:+$('tcBeats').value,tempo:+$('tcTempo').value};}
  function label(q,n){return C.degree(q.scale,n.midi-q.key);}
  function notesHTML(q,original){return q.events.filter(e=>!e.rest).map((e,i)=>{const old=original?.events.filter(n=>!n.rest)[i],changed=old&&(old.note.midi!==e.note.midi||old.start!==e.start||old.duration!==e.duration);return `<div class="training-note ${changed?'changed':''} ${e.target?'target':''}"><strong>${label(q,e.note)}</strong><span>${E.names[E.mod(e.note.midi)]}${Math.floor(e.note.midi/12)-1}</span><small>${e.note.string} 弦 ${e.note.fret} 品</small><small>${e.start/24+1} 拍 · ${e.duration/24} 拍长</small>${e.target?'<small>'+e.target+'</small>':''}</div>`;}).join('');}
  function renderConnection(){stop();$('tcScore').className='connection-results';$('tcScore').innerHTML='<div class="training-actions connection-view">'+field('结果视图','tcView',{tab:'六线谱 · 品位',pitch:'六线谱 · 音名'},'tab')+field('简谱','tcNotation',{movable:'首调 · 调式主音 = 1',fixed:'固定调 · C = 1'},'movable')+'</div><div id="tcBars" class="connection-bars"></div><p id="tcNoteInfo" class="training-help">按拍点从左向右弹；点击音符查看弦品和试听。蓝色为当前和弦根音，边框标记换和弦落点。</p>';
    function draw(){const beats=connected.connection.beats;$('tcBars').innerHTML=connected.harmonies.map((h,i)=>{const notes=connected.events.filter(e=>e.chordIndex===i);return `<article class="connection-bar" data-connection-bar="${i}"><header><strong>${String(i+1).padStart(2,'0')} · ${['I','II','III','IV','V','VI','VII'][h.degree]} ${h.name}</strong><span>${beats} 拍 · ${notes.length} 音 · ${notes[0]?.target||'和弦音'}</span></header>${root.TrainingScore.render(connected,{from:i*beats*24,to:(i+1)*beats*24,notation:$('tcNotation').value,view:$('tcView').value,id:'connection-'+i})}</article>`;}).join('');$('tcBars').querySelectorAll('[data-score-event]').forEach(el=>{el.setAttribute('role','button');el.setAttribute('tabindex','0');const activate=()=>{const e=connected.events[+el.dataset.scoreEvent];$('tcNoteInfo').textContent=E.names[E.mod(e.note.midi)]+' · '+label(connected,e.note)+' · '+e.note.string+' 弦 '+e.note.fret+' 品 · '+e.duration/24+' 拍'+(e.target?' · '+e.target:'');stopOthers();stop();mode='connection';player.preview(e.note.midi,{...audio,guitarVolume:+$('tcVolume').value});};el.onclick=activate;el.onkeydown=e=>{if(e.key==='Enter'||e.code==='Space'){e.preventDefault();e.stopPropagation();activate();}};});}
    $('tcView').onchange=draw;$('tcNotation').onchange=draw;draw();$('tcSection').replaceChildren(new Option('完整进行','all'),...connected.harmonies.map((h,i)=>new Option((i+1)+' · '+h.name,i)));$('tcStatus').textContent=connected.warnings.join(' ')||'已生成 · 每组首音为换和弦落点';$('tcNow').textContent=connected.harmonies.map(h=>h.name).join(' → ');}
  function stop(){player.stop();cancelAnimationFrame(frame);document.querySelectorAll('#tcBars .current,#tcBars .sounding').forEach(el=>el.classList.remove('current','sounding'));}
  function stopOthers(){stopArpeggio();root.GuitarGroove.stop();root.EarTraining.stop();}
  function playConnection(){
    try{if(!connected){connected=T.connection(readConnection());renderConnection();}stopOthers();mode='connection';let q=clone(connected);const section=$('tcSection').value;
      if(section!=='all'){const index=+section,offset=index*q.connection.beats*24;q.events=q.events.filter(e=>e.chordIndex===index).map(e=>({...e,start:e.start-offset}));q.totalTicks=q.connection.beats*24;}
      if(!$('tcDemo').checked)q.events=[];
      player.play(q,{...audio,tempo:connected.config.tempo,repeats:$('tcLoop').checked?0:1,guitarVolume:+$('tcVolume').value});
      const update=()=>{if(player.playing&&player.plan&&player.context&&Number.isFinite(player.firstStart)){const secondsPerTick=60/connected.config.tempo/24,cycleTicks=(section==='all'?connected.totalTicks:connected.connection.beats*24),elapsedTicks=Math.floor(Math.max(0,player.context.currentTime-player.firstStart)/secondsPerTick)%cycleTicks,absoluteTick=section==='all'?elapsedTicks:+section*connected.connection.beats*24+elapsedTicks,index=Math.min(connected.harmonies.length-1,Math.floor(absoluteTick/(connected.connection.beats*24))),localBeat=Math.floor((absoluteTick-index*connected.connection.beats*24)/24);$('tcNow').textContent='当前 '+connected.harmonies[index].name+' · 第 '+(localBeat+1)+' 拍 → 下一 '+connected.harmonies[(index+1)%connected.harmonies.length].name;document.querySelectorAll('#tcBars .current,#tcBars .sounding').forEach(el=>el.classList.remove('current','sounding'));document.querySelector('[data-connection-bar="'+index+'"]')?.classList.add('current');const eventIndex=connected.events.findIndex(e=>e.start<=absoluteTick&&absoluteTick<e.start+e.duration);if(eventIndex>=0)document.querySelector('[data-score-event="'+eventIndex+'"]')?.classList.add('sounding');}if(player.playing||player.preparing)frame=requestAnimationFrame(update);};frame=requestAnimationFrame(update);
    }catch(e){$('tcStatus').textContent=e.message;}
  }
  function safeMotif(fn){try{fn();}catch(e){$('tmStatus').textContent=e.message;}}
  function setSource(q){if(locked)throw Error('原动机 A 已锁定，请先取消锁定。');stop();motif={a:q,b:T.vary(q,$('tmType').value),type:$('tmType').value};syncMotifControls();renderMotif();root.TrainingHub?.exerciseChanged('motif',snapshot('motif'));}
  function makeMotif(){setSource(T.motif({key:+$('tmKey').value,scale:$('tmScale').value,degree:+$('tmDegree').value,tempo:+$('tmTempo').value,min:state.start,max:state.end,phrase:$('tmPhrase').value}));}
  function fromGroove(){const s=root.GuitarGroove.state,c={...s.config,tuning:'standard'};if(s.config.tuning!=='standard')throw Error('动机发展目前使用标准调弦，请先切回标准调弦。');const bar=s.result?.bars[0];if(!bar)throw Error('请先生成律动。');const events=bar.events.filter(e=>e.notes?.length).slice(0,8).map(e=>({start:e.start,duration:e.duration,material:e.material,rest:false,note:clone(e.notes.at(-1)),velocity:e.velocity,gate:e.gate||.85}));setSource(T.question(events,c,Date.now(),{chord:bar.harmony}));}
  function syncMotifControls(){$('tmKey').value=motif.a.key;$('tmScale').value=motif.a.scale;$('tmTempo').value=motif.a.config.tempo;$('tmDegree').value=motif.a.chord?.degree??0;$('tmType').value=motif.type;}
  function renderMotif(){$('tmA').innerHTML=root.TrainingScore.render(motif.a);$('tmB').innerHTML=root.TrainingScore.render(motif.b,{original:motif.a});$('tmGuidance').textContent=({ending:'保留前六个音，只用当前和弦内音改最后两个音。先跟弹 A，再关掉示范，在留白中弹你自己的结尾。',rhythm:'保留所有音高与顺序，只改节奏分配。先拍出新节奏，再放回原来的音。',onset:'保留音高与时值，整体延后半拍进入。先数清 1 和，再从「和」开始。',octave:'保留旋律与节奏，改在可演奏的另一八度回应。比较音区变化，不改变和声。'})[motif.type];$('tmStatus').textContent='A 保持不变 · B '+T.changes[motif.type]+' · '+E.names[motif.a.key]+' '+C.scales[motif.a.scale]+' · '+motif.a.config.tempo+' BPM';}
  function playMotif(which){safeMotif(()=>{if(!motif)makeMotif();stopOthers();mode='motif';const q=which==='a'?motif.a:which==='b'?motif.b:T.combine(motif.a,motif.b,which==='turn');player.play(q,{...audio,tempo:motif.a.config.tempo,repeats:+$('tmRepeat').value,guitarVolume:+$('tmVolume').value});});}
  function load(kind,data){stop();if(kind==='connection'){connected=clone(data);const c=connected?.connection||T.defaults;for(const [id,key]of Object.entries({tcKey:'key',tcScale:'scale',tcProgression:'progression',tcTarget:'target',tcDifficulty:'difficulty',tcStrings:'strings',tcMin:'min',tcMax:'max',tcBeats:'beats',tcTempo:'tempo'}))$(id).value=c[key];if(connected)renderConnection();else{$('tcScore').replaceChildren();$('tcNow').textContent='';$('tcStatus').textContent='自由练习 · 按设置生成连接';}}else{motif=clone(data);locked=!!data;$('tmLock').checked=locked;if(motif){syncMotifControls();renderMotif();}else{$('tmA').replaceChildren();$('tmB').replaceChildren();$('tmStatus').textContent='自由练习 · 先建立原动机';}}}
  function snapshot(kind){return clone(kind==='connection'?connected:motif);}
  function navigate(tool){stop();$('connectionPanel').hidden=tool!=='chord';if(tool!=='chord'&&$('motifModal').classList.contains('open'))closeMotif();}
  root.TrainingStudio={init,stop,navigate,load,snapshot,playConnection,playMotif,installGroove,openMotif,resetMotifView(){setMotifView(false);},toggleMotif(){if(player.playing)stop();else playMotif('ab');},refreshFavorites(items){$('tmFavorites').replaceChildren(new Option('选择收藏',''),...items.map((m,i)=>new Option(E.names[m.a.key]+' '+C.scales[m.a.scale]+' · '+T.changes[m.type]+' · '+(i+1),i)));}};
})(globalThis);
